version: "3.7"

services:
  # Visualize metrics
  grafana:
    hostname: grafana
    image: stefanprodan/swarmprom-grafana:5.3.4
    user: root
    networks:
      - ocariot
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VAULT_BASE_URL=${VAULT_BASE_URL}
      - VAULT_PORT=${VAULT_PORT}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      - GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    ports:
      - 3200:3000
    secrets:
      - source: vault-ca-cert
        target: /tmp/vault/ca.crt
        mode: 0444
    configs:
      - source: ocariot-grafana-config
        target: /etc/grafana/grafana.ini
        mode: 0444
      - source: ocariot-init-grafana-config
        target: /usr/bin/initializing_grafana.sh
        mode: 0755
    volumes:
      - grafana:/var/lib/grafana
      - "./config/ocariot/vault/.tokens/access-token-grafana:/tmp/access-token-grafana"
    entrypoint: initializing_grafana.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  dockerd-exporter:
    image: stefanprodan/caddy
    networks:
      - ocariot
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
#    entrypoint: /bin/sh -c "while true; do sleep 1; done"
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Containers metrics collector
  cadvisor:
    image: google/cadvisor
    networks:
      - ocariot
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Host metrics collector
  node-exporter:
    image: prom/node-exporter:v1.0.0-rc.0
    user: root
    networks:
      - ocariot
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    configs:
      - source: ocariot-init-node-exporter-config
        target: /etc/node-exporter/docker-entrypoint.sh
        mode: 0755
    entrypoint: /etc/node-exporter/docker-entrypoint.sh
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Metrics database
  prometheus:
    image: stefanprodan/swarmprom-prometheus:v2.5.0
    networks:
      - ocariot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
    ports:
      - 9090:9090

secrets:
  vault-ca-cert:
    file: ${VAULT_CA_CERT_PATH}

configs:
  dockerd_config:
    file: config/monitor/dockerd-exporter/Caddyfile
  node_rules:
    file: config/monitor/prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: config/monitor/prometheus/rules/swarm_task.rules.yml
  ocariot-grafana-config:
    file: config/monitor/grafana/grafana.ini
  ocariot-init-grafana-config:
    file: config/monitor/grafana/scripts/initializing_grafana.sh
  ocariot-init-node-exporter-config:
    file: config/monitor/node-exporter/conf/docker-entrypoint.sh

volumes:
  prometheus: {}
  grafana: {}
  alertmanager: {}

networks:
  ocariot:
    external: true
    name: ocariot
    driver_opts:
      encrypted: "true"
