version: "3.7"

services:
  dockerd-exporter:
    image: stefanprodan/caddy
    networks:
      - ocariot
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Containers metrics collector
  cadvisor:
    image: google/cadvisor
    networks:
      - ocariot
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Visualize metrics
  grafana:
    hostname: grafana
    image: stefanprodan/swarmprom-grafana:5.3.4
    user: root
    networks:
      - ocariot
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VAULT_BASE_URL=${VAULT_BASE_URL}
      - VAULT_PORT=${VAULT_PORT}
      #- GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
      #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      #- GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
      #- GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      #- GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      #- GF_SMTP_USER=${GF_SMTP_USER}
      #- GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    ports:
      - 3200:3000
    secrets:
      - source: vault-ca-cert
        target: /tmp/vault/ca.crt
        mode: 0444
    configs:
      - source: ocariot-grafana-config
        target: /etc/grafana/grafana.ini
        mode: 0444
      - source: ocariot-init-grafana-config
        target: /usr/bin/initializing_grafana.sh
        mode: 0755
    volumes:
      - grafana:/var/lib/grafana
      - "./config/ocariot/vault/.tokens/access-token-grafana:/tmp/access-token-grafana"
    entrypoint: initializing_grafana.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 15
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Alerts dispatcher
#  alertmanager:
#    image: stefanprodan/swarmprom-alertmanager:v0.14.0
#    networks:
#      - ocariot
#    environment:
#      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
#      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
#      - SLACK_USER=${SLACK_USER:-alertmanager}
#    command:
#      - '--config.file=/etc/alertmanager/alertmanager.yml'
#      - '--storage.path=/alertmanager'
#    volumes:
#      - alertmanager:/alertmanager
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          - node.role == manager
#      resources:
#        limits:
#          memory: 128M
#        reservations:
#          memory: 64M

#  # Alert manager dashboard
#  unsee:
#    image: cloudflare/unsee:v0.8.0
#    networks:
#      - ocariot
#    environment:
#      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
#    deploy:
#      mode: replicated
#      replicas: 1

  # Host metrics collector
  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    networks:
      - ocariot
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Metrics database
  prometheus:
    image: stefanprodan/swarmprom-prometheus:v2.5.0
    networks:
      - ocariot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
    ports:
      - 9090:9090

secrets:
  vault-ca-cert:
    file: ${VAULT_CA_CERT_PATH}

configs:
  dockerd_config:
    file: config/monitor/dockerd-exporter/Caddyfile
  node_rules:
    file: config/monitor/prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: config/monitor/prometheus/rules/swarm_task.rules.yml
  ocariot-grafana-config:
    file: config/monitor/grafana/grafana.ini
  ocariot-init-grafana-config:
    file: config/monitor/grafana/scripts/initializing_grafana.sh

volumes:
  prometheus: {}
  grafana: {}
  alertmanager: {}

networks:
  ocariot:
    external: true
    name: ocariot
    driver_opts:
      encrypted: "true"
